name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build static website
        run: npm run build
        env:
          VITE_SUPABASE_URL: "https://zukcgoukezoimrpyjokm.supabase.co"
          VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1a2Nnb3VrZXpvaW1ycHlqb2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcwNDgxMzMsImV4cCI6MjEwMjYyNDEzM30.g1zUJ_vLSzsVb0FCfulnW0ursHLwMFyfsNHetPJ62HY"
          VITE_ADMIN_ROUTE: ${{ secrets.ADMIN_ROUTE }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
